### ISSUE TITLE
Single device, multiple entities

### ISSUE THREAD

**Issue by tjorim** [myTselection/TotalEnergiesClubCard#1]
Hi,

Trying this out and works well!
Took me a while to realize i need to use the card number and pin to authenticate, not my account i use in the app.
Something i noticed again (and also remember from your other integrations): you create a new device per entity.
Wouldn't it make more sense to group them? E.g. each card is a device with the 3 entities grouped underneath.

**Comment by myTselection** [comment]
Thanks for feedback!
Indeed the config flow input elements don't show the name correctly yet, to be investigated.

As to the combination of sensors in one device: I don't know (yet) how to achieve this 😉
